name: post_quantum
description: "Dart implementation of NIST's post-quantum algorithm candidates, Kyber and Dilithium."
version: 1.0.0-prerelease.8
repository: https://github.com/tomasagata/post_quantum

environment:
  sdk: ^3.4.0

dependencies:
  hashlib: ^1.16.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
